# apt-file
# Autogenerated from man page /usr/share/man/man1/apt-file.1.gz
complete -c apt-file -s a -l architecture -d 'This option is useful if you search a package for a different architecture fr…'
complete -c apt-file -s c -l config-file -d 'Configuration File; Specify a configuration file to use'
complete -c apt-file -s D -l from-deb -d 'Use contents of the given . deb archives(s) as patterns'
complete -c apt-file -s f -l from-file -d 'Read patterns from the given file(s), one per line'
complete -c apt-file -l filter-origins -d 'Only search indices from the listed origins (e. g.  \\*(L"Debian\\*(R")'
complete -c apt-file -l filter-suites -d 'Only search indices from the listed suites or codenames (e. g'
complete -c apt-file -s F -l fixed-string -d 'Do not expand search pattern with generic characters at pattern\'s start and e…'
complete -c apt-file -l index-names -s I -d 'Only search indexes of the given name(s)'
complete -c apt-file -s i -l ignore-case -d 'Ignore case when searching for pattern'
complete -c apt-file -s l -l package-only -d 'Only display package name; do not display file names'
complete -c apt-file -l stream-results -d 'This is a special-usage option useful for dealing with searches that produce …'
complete -c apt-file -s o -l option -d 'Set a Configuration Option; This will set an arbitrary configuration option'
complete -c apt-file -l substring-match -d 'Match if the given search pattern is a substring of a path or package'
complete -c apt-file -s v -l verbose -d 'Run apt-file in verbose/debug mode'
complete -c apt-file -s x -l regexp -d 'Treat pattern as a (perl) regular expression.  See perlreref\\|(1) for details'

