# erb3.1
# Autogenerated from man page /usr/share/man/man1/erb3.1.1.gz
complete -c 'erb3.1' -l version -d 'Prints the version of erb3. 1.  Pp'
complete -c 'erb3.1' -s E
complete -c 'erb3.1' -l encoding -d 'Specifies the default value(s) for external encodings and internal encoding'
complete -c 'erb3.1' -s P -d 'Disables ruby code evaluation for lines beginning with "%".  Pp'
complete -c 'erb3.1' -s S -d 'Specifies the safe level in which eRuby script will run.  Pp'
complete -c 'erb3.1' -s T -d 'Specifies trim mode (default 0)'
complete -c 'erb3.1' -s r -d 'Load a library Pp'
complete -c 'erb3.1' -s U -d 'can be one of Sets the default value for internal encodings ( Li "Encoding'
complete -c 'erb3.1' -s d
complete -c 'erb3.1' -l debug -d 'Turns on debug mode.  "$DEBUG" will be set to true.  Pp'
complete -c 'erb3.1' -s h
complete -c 'erb3.1' -l help -d 'Prints a summary of the options.  Pp'
complete -c 'erb3.1' -s n -d 'Used with x.  Prepends the line number to each line in the output.  Pp'
complete -c 'erb3.1' -s v -d 'Enables verbose mode.  "$VERBOSE" will be set to true.  Pp'
complete -c 'erb3.1' -s x -d 'Converts the eRuby script into Ruby script and prints it without line numbers'

