# figlet-toilet
# Autogenerated from man page /usr/share/man/man1/figlet-toilet.1.gz
complete -c figlet-toilet -s f -l font -d 'Use the given font instead of the default value.  Fonts are  . flf or  '
complete -c figlet-toilet -s d -l directory -d 'Specify the directory in which to look for fonts'
complete -c figlet-toilet -s s -s S -s k -s W -s o -d 'Select character composition rules'
complete -c figlet-toilet -s w -l width -d 'Set the output width'
complete -c figlet-toilet -s t -l termwidth -d 'Set the output width to the terminal width'
complete -c figlet-toilet -l gay -l metal -d 'PD Specify a list of filters to be applied to the output'
complete -c figlet-toilet -l irc -l html -d 'PD Specify the output format'
complete -c figlet-toilet -s h -l help -d 'Display a short help message and exit'
complete -c figlet-toilet -s I -l infocode -d 'Print a  FIGlet infocode'
complete -c figlet-toilet -s F -l filter
complete -c figlet-toilet -s E -l export
complete -c figlet-toilet -s v -l version -d 'Output version information and exit.  EXAMPLES toilet Hello World'

