# figlet-figlet
# Autogenerated from man page /usr/share/man/man6/figlet-figlet.6.gz
complete -c figlet-figlet -s f -d 'Select the font.   The  '
complete -c figlet-figlet -s d -d 'Change the default font directory'
complete -c figlet-figlet -s x -d 'PD These options handle the justification of  FIGlet output'
complete -c figlet-figlet -s w -d 'PD These options control the R outputwidth , or the screen width  FIGlet assu…'
complete -c figlet-figlet -s n -d 'PD These options control how  FIGlet handles newlines'
complete -c figlet-figlet -s E -d 'PD  -D switches to the German (ISO 646-DE) character set'
complete -c figlet-figlet -s N -d 'PD These options deal with  FIGlet R controlfiles '
complete -c figlet-figlet -s W -d PD
complete -c figlet-figlet -s o -d 'PD These options control how  FIGlet spaces the FIGcharacters that it outputs'
complete -c figlet-figlet -s m -d 'Specifies an explicit  layoutmode between  1 and  63 '
complete -c figlet-figlet -s I -d 'PD These options print various information about  FIGlet , then exit'
complete -c figlet-figlet -s 1 -d 'This  infocode indicates that  FIGlet should operate normally, not giving any…'
complete -c figlet-figlet -s c
complete -c figlet-figlet -s k
complete -c figlet-figlet -s t
complete -c figlet-figlet -s p -d and
complete -c figlet-figlet -s v
complete -c figlet-figlet -o I3 -d option
complete -c figlet-figlet -o I2 -d option
complete -c figlet-figlet -s l
complete -c figlet-figlet -s r
complete -c figlet-figlet -s L
complete -c figlet-figlet -s R -d and
complete -c figlet-figlet -s X
complete -c figlet-figlet -s D
complete -c figlet-figlet -s C
complete -c figlet-figlet -s s
complete -c figlet-figlet -s S
complete -c figlet-figlet -o m0 -d 'is equivalent to'
complete -c figlet-figlet -o m-1 -d 'is equivalent to'
complete -c figlet-figlet -o m-2 -d 'is equivalent to'
complete -c figlet-figlet -s F -d 'option is given on the command line'

