# pamaddnoise
# Autogenerated from man page /usr/share/man/man1/pamaddnoise.1.gz
complete -c pamaddnoise -o type -d 'Select type of noise by name'
complete -c pamaddnoise -o lambda -d 'This is valid only with -type=poisson'
complete -c pamaddnoise -o lsigma -d 'This is menaingful only for laplacian noise. sp The default value is 10. 0'
complete -c pamaddnoise -o mgsigma -d 'This is valid only for multiplicative gaussian noise'
complete -c pamaddnoise -o seed -d 'This is the random number generator seed value'
complete -c pamaddnoise -o sigma1 -d 'This is valid only for gaussian noise'
complete -c pamaddnoise -o sigma2 -d 'This is valid only for gaussian noise'
complete -c pamaddnoise -o tolerance -d 'This is valid only for impulse noise'
complete -c pamaddnoise -o salt -d 'This is valid only for impulse noise'

