# pamcat
# Autogenerated from man page /usr/share/man/man1/pamcat.1.gz
complete -c pamcat -o topbottom -o tb -d 'Combine images vertically, top to bottom'
complete -c pamcat -o leftright -o lr -d 'Combine images horizontally, left to right'
complete -c pamcat -o jleft -d 'Left-justify images in a top-bottom concatenation'
complete -c pamcat -o jright -d 'Right-justify images in a top-bottom concatenation'
complete -c pamcat -o jtop -d 'Top-justify images in a left-right concatenation'
complete -c pamcat -o jbottom -d 'Bottom-justify images in a left-right concatenation'
complete -c pamcat -o jcenter -d 'Center images (valid for both left-right and top-bottom concatenations)'
complete -c pamcat -o white -d 'Make all padding white. sp You may not specify this with -black'
complete -c pamcat -o black -d 'Make all padding black. sp You may not specify this with -white'
complete -c pamcat -o listfile -d 'This specifies the name of a file that contains the list of input files'

