# pamrestack
# Autogenerated from man page /usr/share/man/man1/pamrestack.1.gz
complete -c pamrestack -o width -d 'The width of the output'
complete -c pamrestack -o trim -d 'This option specifies what to do when the new width does not cleanly divide t…'
complete -c pamrestack -o verbose -d 'Print information about the processing to Standard Error'

