# pamseq
# Autogenerated from man page /usr/share/man/man1/pamseq.1.gz
complete -c pamseq -o tupletype -d 'This is the value of the "tuple_type" attribute of the created PAM image'
complete -c pamseq -o min -d 'This gives the starting value for the sequence in each plane'
complete -c pamseq -o max -d 'sp This is analogous to -min, giving the ending value for the     sequence'
complete -c pamseq -o step -d 'sp This is analogous to -min, giving the step value for the     sequence (dif…'

