# pamstack
# Autogenerated from man page /usr/share/man/man1/pamstack.1.gz
complete -c pamstack -o tupletype -d 'This specifies the tuple type name to be recorded in the output'
complete -c pamstack -o firstmaxval -d 'This says to make the maxval of the output the same as the maxval of the firs…'
complete -c pamstack -o lcmmaxval -d 'This says to make the maxval of the output the least common multiple of the m…'

