# pamshuffle
# Autogenerated from man page /usr/share/man/man1/pamshuffle.1.gz
complete -c pamshuffle -o column -d 'Shuffle vertical columns, i. e.  perform the same movement on all rows'
complete -c pamshuffle -o randomseed -d 'This is the seed for the random number generator that generates the pixels'

