# pamtable
# Autogenerated from man page /usr/share/man/man1/pamtable.1.gz
complete -c pamtable -o tuple -d 'Print the tuple values in mathematical tuple notation, like this:  '
complete -c pamtable -o hex -d 'Display sample values in hexadecimal instead of decimal'
complete -c pamtable -o verbose -d 'sp Print additional messages about the processing'

