# pamtopdbimg
# Autogenerated from man page /usr/share/man/man1/pamtopdbimg.1.gz
complete -c pamtopdbimg -o title -d 'The title of the image, to be included in the image'
complete -c pamtopdbimg -o maybecompressed -d 'You may specify only one of these'
complete -c pamtopdbimg -o 4depth -d 'This option makes pamtopdbimg create the image in 16-level grayscale (4 bits …'
complete -c pamtopdbimg -o notefile -d 'Attach the note in the specified file to the image'
complete -c pamtopdbimg -o fixedtime -d 'Fake the mtime and ctime vaues in the PDB image with a value that is the same…'
complete -c pamtopdbimg -o compressed
complete -c pamtopdbimg -o uncompressed

