# pbmmake
# Autogenerated from man page /usr/share/man/man1/pbmmake.1.gz
complete -c pbmmake -o gray -d 'sp These options specify the color of the output'
complete -c pbmmake -o white
complete -c pbmmake -o black

