# ppmrough
# Autogenerated from man page /usr/share/man/man1/ppmrough.1.gz
complete -c ppmrough -o width -d 'This specifies the width of the image in pixels (default: 100)'
complete -c ppmrough -o height -d 'This specifies the height of the image in pixels (default: 100)'
complete -c ppmrough -o bottom -d 'This option causes the program to create a left, right, top, or bottom border…'
complete -c ppmrough -o bg -d 'This is the background color, i. e.  the color of the borders'
complete -c ppmrough -o fg -d 'This specifies the foreground color, i. e'
complete -c ppmrough -o var -d 'This specifies how ragged the borders are -- how much and how quickly its wid…'
complete -c ppmrough -o randomseed -d 'Use this option to initialize the pseudo-random number generator with seed'
complete -c ppmrough -o verbose -d 'Run ppmrough in verbose mode.   It reports all parameters on Standard Error'
complete -c ppmrough -o left
complete -c ppmrough -o right
complete -c ppmrough -o top

