# regexp-assemble.1p
# Autogenerated from man page /usr/share/man/man1/regexp-assemble.1p.gz
complete -c 'regexp-assemble.1p' -s a -d 'look Ahead.  Insert \\f(CW\\*(C`(?='
complete -c 'regexp-assemble.1p' -s b -d 'Blank.  Ignore blank lines'
complete -c 'regexp-assemble.1p' -s c -d 'Comment.  Basic comment filtering'
complete -c 'regexp-assemble.1p' -s d -d 'Debug.  Turns on debugging output.  See Regexp::Assemble for suitable values'
complete -c 'regexp-assemble.1p' -s i -d Indent
complete -c 'regexp-assemble.1p' -s n -d 'No newline.  Do not print a newline after the pattern'
complete -c 'regexp-assemble.1p' -s p -d 'Print.  Print the pattern'
complete -c 'regexp-assemble.1p' -s r -d 'Reduce.  The default behaviour is to reduce the assembled pattern'
complete -c 'regexp-assemble.1p' -s s -d 'Statistics.  Print some statistics about the assembled pattern'
complete -c 'regexp-assemble.1p' -s S -d 'Statistics only.  Like -s, except that the pattern itself is not output'
complete -c 'regexp-assemble.1p' -s t -d 'Test.  Test the assembled expression against the contents of a file'
complete -c 'regexp-assemble.1p' -s T -d 'Time.  Print statistics on the time taken to reduce and assemble the pattern'
complete -c 'regexp-assemble.1p' -s u -d 'Unique.  Carp if duplicate patterns are found'
complete -c 'regexp-assemble.1p' -s U -d Unroll
complete -c 'regexp-assemble.1p' -s v -d 'Version.  Print the version of the regexp-assemble script'

