# ukify
# Autogenerated from man page /usr/share/man/man1/ukify.1.gz
complete -c ukify -l initrd -d 'can be specified multiple times'
complete -c ukify -l section -d below
complete -c ukify -l phases -d and
complete -c ukify -l pcr-private-key -d 'are used, they must be specified the same number of times, and then the n-th …'
complete -c ukify -l some-setting
complete -c ukify -l config
complete -c ukify -l measure -l no-measure
complete -c ukify -l tools
complete -c ukify -l output
complete -c ukify -l summary
complete -c ukify -s h -l help
complete -c ukify -l version
complete -c ukify -l engine -d 'option of sbsign(1).  SignKernel=BOOL, --sign-kernel, --no-sign-kernel'

