# update-command-not-found
# Autogenerated from man page /usr/share/man/man8/update-command-not-found.8.gz
complete -c update-command-not-found -s h -l help -d 'Print the help message'
complete -c update-command-not-found -s n -l no-apt-file -d 'Do not run apt-file update before updating the cache'

